#!/usr/bin/env bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -e|--posts)
    POSTS="$2"
    shift # past argument
    shift # past value
    ;;
esac
done
set -- "${POSITIONAL[@]}"


mvn clean package >/dev/null

java -jar target/hacker-news-scraper-1.0-SNAPSHOT-jar-with-dependencies.jar --posts $POSTS
